# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf

input { # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = us,us
    kb_variant = altgr-intl,rus
    kb_options = grp:ctrl_space_toggle, compose:rctrl, caps:escape, shift:both_capslock
}
