#...
starship init fish | source
# comment out to remove autogenerated colors
#if test -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt
#    cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
#end
#...