#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#tempwallpaper
feh --bg-fill ~/Pictures/blueishFaded1.png &

#temppicom
#picom -f -b &

#temptouchpadsettings
xinput set-prop "SYNA32A9:00 06CB:CE17 Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "SYNA32A9:00 06CB:CE17 Touchpad" "libinput Natural Scrolling Enabled" 1 &&

bspc config normal_border_color "#1E1E32"
bspc config active_border_color "#3D3D66"
bspc config focused_border_color "#7A52CC"
bspc config presel_feedback_color "#7A52CC"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config border_width        10
bspc config window_gap          40

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
